name-template: 'Play $NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
filter-by-commitish: true
commitish: 2.8.x

change-template: '- $TITLE #$NUMBER by @$AUTHOR'
template: |
  The Play Team is happy to announce the release of Play $NEXT_PATCH_VERSION.
  
  ## :green_book: What is new?
  
  The following are the relevant changes of this bugfix release:
  
  * TODO [#123](https://github.com/playframework/playframework/pull/123)
  * TODO [#123](https://github.com/playframework/playframework/issues/123)
  
  Following pull requests got merged for this release:
  
  $CHANGES
  
  For more details see the [full list of changes](https://github.com/playframework/playframework/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION/) and the [$NEXT_PATCH_VERSION milestone](https://github.com/playframework/playframework/issues?page=1&q=milestone%3A%22$NEXT_PATCH_VERSION%22).
  
  ## Migration
  
  TODO (please fill in or remove this heading)

  ## :heart: Thanks to our premium sponsors!

  <div align="center">
    <a href="https://informaticon.com/"><img src="https://www.playframework.com/assets/images/home/sponsors/61220b8306493af6a21b7db17de7f4b2-informaticon-logo-full-color.png" width="250"></a>
    <a href="https://cedarlakeventures.com/"><img src="https://www.playframework.com/assets/images/home/sponsors/bec2b526c9ce52c051f9089a10044867-cedar-lake-ventures.png" width="250"></a>
    <a href="https://iterable.com/"><img src="https://www.playframework.com/assets/images/home/sponsors/61ddb4c3665b621e6672181f97196748-iterable.png" width="250"></a>
  </div>

  If you find Play useful for work, please consider asking your company to support this Open Source project by <a href="https://www.playframework.com/sponsors">becoming a sponsor</a>.
  You can also individually sponsor the project by <a href="https://www.playframework.com/sponsors">becoming a backer</a>.

  <div align="center">
    <a href="https://opencollective.com/playframework" target="_blank">
      <img src="https://opencollective.com/playframework/donate/button@2x.png?color=blue" width="250" />
    </a>
  </div>
  
  ## :bow: Thanks to our contributors
  
  Finally, thanks to the community for their help with detailed bug reports, discussion about new features, and pull requests review. Play is only possible due to the help we had from amazing contributors.
  Special thanks to all code contributors who helped with this particular release (they are listed below)!
