# Only build non-pushes (so PRs, API requests & cron jobs) OR tags OR forks OR main branch builds
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: type != push OR tag IS present OR repo != playframework/playframework OR branch IN (main, 2.8.x, 2.7.x, 2.6.x)

env:
  global:
    - secure: "NS2hMbBcmi6EF4QxtcNs4A2ZuNmIdLYQRJUWWejgnD4YtcsmoVjxrHRedqrnDdui4DyvaxWhg/3Uds23jEKTSbbh3ZphLO77BVgM2nUGUvVoa4i6qGF2eZFlIhq2G1gM700GPV7X4KmyjYi2HtH8CWBTkqP3g0An63mCZw/Gnlk="
    # These are the versions used for (scripted) tests. The versions Play is build with however are defined in interplay.
    - SCRIPTED_SBT_1_6: "1.6.2"
    - TEST_SCALA_2_13: "2.13.8"
  jobs:
    - TRAVIS_JDK=11

stages:
  - validations
  - test
  - test-sbt-1.6.x
  - java8

jobs:
  include:
    - stage: validations
      name: "Run publishLocal"
      script: scripts/publish-local
      workspaces:
        create:
          name: published-local
          paths: "$HOME/.ivy2/local/com.typesafe.play"
    - name: "Run publishLocal on Java 8"
      script: scripts/publish-local
      env: TRAVIS_JDK=8
      workspaces:
        create:
          name: published-local-jdk8
          paths: "$HOME/.ivy2/local/com.typesafe.play"

    - stage: test-sbt-1.6.x
      name: "Run scripted tests (a) for sbt 1.6.x and Scala 2.13.x"
      script: scripts/test-scripted $SCRIPTED_SBT_1_6 $TEST_SCALA_2_13 'play-sbt-plugin/*1of3'
      workspaces:
        use: published-local
    - name: "Run scripted tests (b) for sbt 1.6.x and Scala 2.13.x"
      script: scripts/test-scripted $SCRIPTED_SBT_1_6 $TEST_SCALA_2_13 'play-sbt-plugin/*2of3'
      workspaces:
        use: published-local
    - name: "Run scripted tests (c) for sbt 1.6.x and Scala 2.13.x"
      script: scripts/test-scripted $SCRIPTED_SBT_1_6 $TEST_SCALA_2_13 'play-sbt-plugin/*3of3'
      workspaces:
        use: published-local
